# Generated by Django 2.0.2 on 2018-05-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20180430_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctfeedback',
            name='correct_text',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tasks.ReelCorrectText'),
        ),
        migrations.AlterField(
            model_name='correctseg',
            name='task',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='diffseg',
            name='reeldiff',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.ReelDiff'),
        ),
        migrations.AlterField(
            model_name='diffsegresult',
            name='diffseg',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='diffsegresults', to='tasks.DiffSeg'),
        ),
        migrations.AlterField(
            model_name='diffsegresult',
            name='task',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='diffsegtext',
            name='diffseg',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='diffsegtexts', to='tasks.DiffSeg'),
        ),
        migrations.AlterField(
            model_name='doubtseg',
            name='task',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='doubt_segs', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='judgefeedback',
            name='diffsegresult',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tasks.DiffSegResult'),
        ),
        migrations.AlterField(
            model_name='lqpunct',
            name='lqreel',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tdata.LQReel', verbose_name='龙泉藏经卷'),
        ),
        migrations.AlterField(
            model_name='lqpunct',
            name='reeltext',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tasks.LQReelText', verbose_name='龙泉藏经卷经文'),
        ),
        migrations.AlterField(
            model_name='lqpunct',
            name='task',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Task', verbose_name='发布任务'),
        ),
        migrations.AlterField(
            model_name='lqpunctfeedback',
            name='lqpunct',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tasks.LQPunct', verbose_name='定本标点'),
        ),
        migrations.AlterField(
            model_name='lqreeltext',
            name='lqreel',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tdata.LQReel', verbose_name='龙泉藏经卷'),
        ),
        migrations.AlterField(
            model_name='lqreeltext',
            name='task',
            field=models.OneToOneField(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Task', verbose_name='发布任务'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='reel',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tdata.Reel'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='reeltext',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tasks.ReelCorrectText', verbose_name='实体藏经卷经文'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='task',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Task', verbose_name='发布任务'),
        ),
        migrations.AlterField(
            model_name='markunit',
            name='mark',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tasks.Mark'),
        ),
        migrations.AlterField(
            model_name='punct',
            name='reel',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tdata.Reel', verbose_name='实体藏经卷'),
        ),
        migrations.AlterField(
            model_name='punct',
            name='reeltext',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tasks.ReelCorrectText', verbose_name='实体藏经卷经文'),
        ),
        migrations.AlterField(
            model_name='punct',
            name='task',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Task', verbose_name='发布任务'),
        ),
        migrations.AlterField(
            model_name='reelcorrecttext',
            name='reel',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reel_correct_texts', to='tdata.Reel', verbose_name='实体藏经卷'),
        ),
        migrations.AlterField(
            model_name='reelcorrecttext',
            name='task',
            field=models.OneToOneField(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Task', verbose_name='发布任务'),
        ),
        migrations.AlterField(
            model_name='reeldiff',
            name='base_text',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reeldiffs', to='tasks.ReelCorrectText', verbose_name='基准文本'),
        ),
        migrations.AlterField(
            model_name='reeldiff',
            name='lqsutra',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tdata.LQSutra'),
        ),
        migrations.AlterField(
            model_name='task',
            name='base_reel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tdata.Reel', verbose_name='底本'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lqreel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tdata.LQReel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lqtext',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lqpunct_tasks', to='tasks.LQReelText', verbose_name='龙泉藏经卷经文'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tdata.Reel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reeldiff',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.ReelDiff'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reeltext',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punct_tasks', to='tasks.ReelCorrectText'),
        ),
    ]
